# coding:utf-8
__author__ = 'Johnny'

# 查询审批总额SQL
QUERY_SUM_AMOUNT_BY_USER = ("SELECT anon_1.oa_reimbursement_id AS id,"
                            "anon_1.oa_reimbursement_approval AS approval,"
                            "anon_1.oa_reimbursement_approval_type AS approval_type,"
                            "anon_1.oa_reimbursement_project_id AS project_id,"
                            "anon_1.oa_reimbursement_org_id AS org_id,"
                            "sum(anon_1.oa_reimbursement_amount) AS amount,"
                            "anon_1.oa_reimbursement_describe AS describ,"
                            "anon_1.oa_reimbursement_reason AS reason,"
                            "anon_1.oa_reimbursement_start_date AS start_date,"
                            "anon_1.oa_reimbursement_end_date AS end_date,"
                            "anon_1.oa_reimbursement_is_refuse AS is_refuse,"
                            "anon_1.oa_reimbursement_is_retreat AS is_retreat,"
                            "anon_1.oa_reimbursement_fail_reason AS fail_reason,"
                            "anon_1.oa_reimbursement_is_paid AS is_paid,"
                            "anon_1.oa_reimbursement_paid_date AS paid_date,"
                            "anon_1.oa_reimbursement_create_user AS create_user,"
                            "anon_1.oa_reimbursement_create_date AS create_date,"
                            "anon_1.oa_reimbursement_modify_user AS modify_user,"
                            "anon_1.oa_reimbursement_modify_date AS modify_date"
                            " FROM "
                            "("
                            " SELECT "
                            "oa_reimbursement.id AS oa_reimbursement_id,"
                            "oa_reimbursement.approval AS oa_reimbursement_approval,"
                            "oa_reimbursement.approval_type AS oa_reimbursement_approval_type,"
                            "oa_reimbursement.project_id AS oa_reimbursement_project_id,"
                            "oa_reimbursement.org_id AS oa_reimbursement_org_id,"
                            "oa_reimbursement.amount AS oa_reimbursement_amount,"
                            "oa_reimbursement.describe AS oa_reimbursement_describe,"
                            "oa_reimbursement.reason AS oa_reimbursement_reason,"
                            "oa_reimbursement.start_date AS oa_reimbursement_start_date,"
                            "oa_reimbursement.end_date AS oa_reimbursement_end_date,"
                            "oa_reimbursement.is_refuse AS oa_reimbursement_is_refuse,"
                            "oa_reimbursement.is_retreat AS oa_reimbursement_is_retreat,"
                            "oa_reimbursement.fail_reason AS oa_reimbursement_fail_reason,"
                            "oa_reimbursement.is_paid AS oa_reimbursement_is_paid,"
                            "oa_reimbursement.paid_date AS oa_reimbursement_paid_date,"
                            "oa_reimbursement.create_user AS oa_reimbursement_create_user,"
                            "oa_reimbursement.create_date AS oa_reimbursement_create_date,"
                            "oa_reimbursement.modify_user AS oa_reimbursement_modify_user,"
                            "oa_reimbursement.modify_date AS oa_reimbursement_modify_date"
                            " FROM "
                            "oa_reimbursement"
                            " WHERE "
                            "is_paid = 0"
                            " AND is_refuse = 0"
                            " AND approval_type = 2"
                            " AND approval IN ("
                            " SELECT "
                            "id"
                            " FROM "
                            "oa_project"
                            " WHERE "
                            "manager_id = %s"
                            " AND version = '2015'"
                            ")"
                            " UNION "
                            " SELECT "
                            "oa_reimbursement.id AS oa_reimbursement_id,"
                            "oa_reimbursement.approval AS oa_reimbursement_approval,"
                            "oa_reimbursement.approval_type AS oa_reimbursement_approval_type,"
                            "oa_reimbursement.project_id AS oa_reimbursement_project_id,"
                            "oa_reimbursement.org_id AS oa_reimbursement_org_id,"
                            "oa_reimbursement.amount AS oa_reimbursement_amount,"
                            "oa_reimbursement.describe AS oa_reimbursement_describe,"
                            "oa_reimbursement.reason AS oa_reimbursement_reason,"
                            "oa_reimbursement.start_date AS oa_reimbursement_start_date,"
                            "oa_reimbursement.end_date AS oa_reimbursement_end_date,"
                            "oa_reimbursement.is_refuse AS oa_reimbursement_is_refuse,"
                            "oa_reimbursement.is_retreat AS oa_reimbursement_is_retreat,"
                            "oa_reimbursement.fail_reason AS oa_reimbursement_fail_reason,"
                            "oa_reimbursement.is_paid AS oa_reimbursement_is_paid,"
                            "oa_reimbursement.paid_date AS oa_reimbursement_paid_date,"
                            "oa_reimbursement.create_user AS oa_reimbursement_create_user,"
                            "oa_reimbursement.create_date AS oa_reimbursement_create_date,"
                            "oa_reimbursement.modify_user AS oa_reimbursement_modify_user,"
                            "oa_reimbursement.modify_date AS oa_reimbursement_modify_date"
                            " FROM "
                            "oa_reimbursement"
                            " WHERE "
                            "is_paid = 0"
                            " AND approval_type = 1"
                            " AND org_id IN ("
                            "SELECT "
                            "id"
                            " FROM "
                            "oa_org"
                            " WHERE "
                            "manager = %s"
                            " AND version = '2015'"
                            ")"
                            ") AS anon_1"
                            " GROUP BY "
                            "anon_1.oa_reimbursement_create_user"
                            )